---
apiVersion: apps/v1beta2
kind: Deployment # what kind of manifest this is
metadata:
  name: nginx-deployment # this gives the deployment a name
  labels:
    app: nginx # this used to default to template.metadata.labels, but now you have to set it
spec: # sets the desired state of what we want
  replicas: 3 # says to create 3 pods
  selector: # this must match template.metadata.labels
    matchLabels:
      app: nginx
  template: # describes how to create the pod
    metadata:
      labels:
        app: nginx
    spec: # the details about how to create the pod
      containers:
        - name: nginx # name of the pod
          image: nginx:1.7.9 # Docker image to pull
          ports:
            - containerPort: 80 # open port 80 on the pod
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  type: NodePort
  selector:
    app: nginx