---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-configmap
  namespace: dev
data:
  influxdb.conf: |-
    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"

---
apiVersion: apps/v1beta2
kind: Deployment 
metadata:
  name: influxdb 
  namespace: dev
  labels:
    app: influxdb 
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: influxdb
  template: 
    metadata:
      labels:
        app: influxdb
      namespace: dev
    spec:
      containers:
      - name: influxdb 
        image: influxdb
        ports:
        - containerPort: 8086
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-data-vol
        - mountPath: /etc/influxdb
          name: influxdb-config-vol
      volumes:
      - name: influxdb-data-vol
        emptyDir: {}
      - name: influxdb-config-vol
        configMap:
          name: influxdb-configmap
          items:
          - key: influxdb.conf
            path: influxdb.conf

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: dev
  labels:
    app: influxdb
spec:
  ports:
  - port: 8086
    protocol: TCP
  type: NodePort
  selector:
    app: influxdb

---
apiVersion: apps/v1beta2
kind: Deployment 
metadata:
  name: grafana 
  namespace: dev
  labels:
    app: grafana 
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: grafana
  template: 
    metadata:
      labels:
        app: grafana
      namespace: dev
    spec:
      containers:
      - name: grafana 
        image: grafana/grafana:4.6.3
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: dev
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: NodePort
  selector:
    app: grafana