---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ingress-default-backend
  namespace: dev
  labels:
    app: defaultserver 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: defaultserver
  template: 
    metadata:
      namespace: dev
      labels:
        app: defaultserver
    spec: 
      containers:
      - name: ingress-default-backend
        image: gcr.io/google_containers/defaultbackend:1.0 
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-default-backend-service
  namespace: dev
  labels:
    app: defaultserver
spec:
  selector:
    app: defaultserver
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress-configmap 
  namespace: dev
data:
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-configmap
  namespace: dev
data:
  telegraf.conf: |-
    [[outputs.influxdb]]
      urls = ["http://influxdb-service.dev.svc.cluster.local:8086"]
      database = "haproxy"

    [[inputs.haproxy]]
      servers = ["http://localhost:1936"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-ingress
  namespace: dev
  labels:
    run: haproxy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
      name: haproxy-ingress
      namespace: dev
    spec:
      serviceAccountName: ingress-controller
      containers:
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress:latest
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend-service
        - --default-ssl-certificate=$(POD_NAMESPACE)/tls-secret
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          value: dev
      - name: telegraf
        image: telegraf
        volumeMounts:
        - mountPath: /etc/telegraf
          name: telegraf-vol
      volumes:
        - name: telegraf-vol
          configMap:
            name: telegraf-configmap
            items:
            - key: telegraf.conf
              path: telegraf.conf

---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-service
  namespace: dev
  labels:
    run: haproxy-ingress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: stats
    port: 1936
    protocol: TCP
  type: NodePort
  selector:
    run: haproxy-ingress
      